h1[0]=A
h1[image]=kathara/base
h2[0]=B
h2[image]=kathara/base

h3[0]=K
h3[image]=kathara/base
h4[0]=L
h4[image]=kathara/base

sf1[0]=F
sf1[image]=service_function
sf2[0]=G
sf2[image]=service_function

sf3[0]=Q
sf3[image]=service_function

a[0]=A
a[1]=B
a[2]=C
a[3]=D
a[image]=kathara/p4

b[0]=C
b[1]=E
b[2]=I
b[3]=S
b[image]=kathara/p4

c[0]=D
c[1]=S
c[2]=O
c[3]=R
c[image]=kathara/p4

d[0]=F
d[1]=G
d[2]=H
d[3]=E
d[image]=kathara/p4

e[0]=Q
e[1]=R
e[2]=P
e[image]=kathara/p4

f[0]=H
f[1]=J
f[2]=N
f[3]=I
f[image]=kathara/p4

g[0]=P
g[1]=O
g[2]=N
g[3]=M
g[image]=kathara/p4

h[0]=J
h[1]=K
h[2]=L
h[3]=M
h[image]=kathara/p4
